version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            - v1-dependencies-
      - run: clojure -Rkaocha -Stree
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
      - run: chmod +x bin/kaocha
      - run: bin/kaocha unit
