version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-node-browsers
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            - v1-dependencies-
      - run:
          name: Env setup
          command: |
            echo 'export PATH=$PWD/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc
            chmod +x bin/kaocha
      - run:
          name: Clojure unit tests
          command: kaocha unit
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
